### PR TITLE
Added-music.mp3-music_credits.txt-copyright free

### PR DESCRIPTION
**Pull request by yashkurkure**
Duration of music: 3min 19 sec.

Credits to music.mp3 file:
Music: Tobu & AhXon - In My Mind
http://youtube.com/tobuofficial
AhXon
https://instagram.com/ahxonmusic

### CODE REVIEW

**Comment by divyanshTyagi** [comment]
i was thinking of something lo-fi

**Comment by yashkurkure** [comment]
Ahh okay. How about this: https://www.youtube.com/watch?v=wAukvwLCVbM
I like this one, it happened to be copyright-free.

**Comment by divyanshTyagi** [comment]
if you could find something for 5 ish minutes, that would be great, otherwise ill just put this one on loop for the time being

**Comment by divyanshTyagi** [comment]
or we could maintain more than one music file, keep adding to it over time.

**Comment by divyanshTyagi** [comment]
> 
> 
> Ahh okay. How about this: https://www.youtube.com/watch?v=wAukvwLCVbM
> I like this one, it happened to be copyright-free.
> The duration is 1min 45 sec, is that enough?

Create a pull request for this, ill add it.

**Comment by yashkurkure** [comment]
I found an extended version of 10 min of the same song: https://www.youtube.com/watch?v=nnjVB_EMCl8
Should I create a pull request with this one?

**Comment by divyanshTyagi** [comment]
Merged!

**Pull request merged**
